program: killifish.py
project: kf-dtd-231022
command:
  - ${interpreter}
  - ${program}
  - "${envvar:DATADIR}"
  - "--outdir=${envvar:OUTDIR}"
  - "--drop_last"
  - "--wandb"
  - ${args}
method: grid
parameters:
  method:
    value: full
  epoch:
    value: 2500
  alpha:
    value: 1.1
  k1:
    values: [10,20,30,40,50]
  k2:
    values: [5,10,15,20,25]
  k3:
    values: [10,20,30,40,50]
